### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by eashwarsiddharth** [sagitechls/SSN_SACE_2017_Jan#1]
Do you by any chance have a schema like representation for the data files ?

@sagitechls @Rajhan

**Comment by Rajhan** [comment]
Prescriber tables-> contains drugs prescribed, its cost, no.of beneficiaries, claim count etc.,
PUF tables-> describes the procedures performed and services rendered by docs.
PUF.pres.conso-> derived data from puf and prescriber tables.

**Comment by Rajhan** [comment]
refer the PDF files for the methodology used in building these tables.

**Comment by Rajhan** [comment]
@eashwarsiddharth 
ML algorithms that can be applied to the given datasets.

Classification

Prescriber of Avonex vs Copaxone
Prescribers of Gilenya vs Copaxone
Prescribers of Branded vs Generics
Prediction
Prescribers of Namenda
Prescribers of Generics
