### ISSUE TITLE
Same drug_name, multiple generic_name

### ISSUE THREAD

**Issue by eashwarsiddharth** [sagitechls/SSN_SACE_2017_Jan#17]
**Although the variation in the generic name is not too distinctive, should I do further EDA on this ?**
**They are sometimes done by the same doc-**

**Eg;**
{{SURE COMFORT SYRING W-NDL,DISP,INSUL,0.5 ML
&
SYRINGE & NEEDLE,INSULIN,1 ML} for drug_name {SURE COMFORT}} @AX2130171

{{ONDANSETRON HCL
&
ONDANSETRON HCL/PF} for drug_name {ONDANSETRON HCL} @AX7511504

**Total no. of drug_names = 22** each with 2 generic names

Code @Day_4

**Comment by Rajhan** [comment]
can you list other 20 drugs? but for the above-listed drugs, the generic name is still same.( example a drug can be in solid or liquid form but still same.)

**Comment by eashwarsiddharth** [comment]
The following code will give you a list of all such drugs;
```
drug_name_anomaly_4 %>% lapply(FUN = function(x){
                                x %>% select(drug_name, generic_name) %>% unique()
                              })
```

Please check it out and let me know if modify the generic names.
