### ISSUE TITLE
PUF_detailed: HCPCS_code duplicated for docs

### ISSUE THREAD

**Issue by eashwarsiddharth** [sagitechls/SSN_SACE_2017_Jan#20]
In several cases such as;
- doc_id == 'XZ8826672' & hcpcs_code == '99205'
- doc_id == 'OH4026307' & hcpcs_code == '99215'

The numeric values in the table seem to causing discrepancies. I have created a bar chart based on proportion of such instances as a visual aid.
@Rajhan Would you recommend pursuing this ?

**Comment by Rajhan** [comment]
That's not an issue. A physician can do any procedure for any number times. This dataset is created from claims master data submitted by each physician. So in a given year, he might have submitted records at multiple times. So aggregate data based on procedure codes for each physician.
