### ISSUE TITLE
Handling state == 'ZZ'

### ISSUE THREAD

**Issue by eashwarsiddharth** [sagitechls/SSN_SACE_2017_Jan#3]
state == 'ZZ' corresponds to cities in a foreign country and there are only 48 such records. Any suggestion on how to handle them ?

> The doc_id's in these records are unique to the specified city and state and these cities are unique to state == 'ZZ'.

@sagitechls @Rajhan

**Comment by ANANDHSHANKARSUNDARARAJAN** [comment]
@eashwarsiddharth  It refers to the city of Jaipur in India and Particular Doctor of id  SR7876440 who gives services only in India. 
If you Problem statement is regarding Provider comparison you can visualize the prescription by US Doctors and Indian Doctors for the Certain Diseases and can Generate decision making Inferences about  Doctor's Treatment Region wise.

**Comment by eashwarsiddharth** [comment]
@ANANDHSHANKARSUNDARARAJAN 
There are a few other places like St.John's (1), Dartmouth (5) and Toronto (7). On the whole there are only 48 records and I thought our scope was only the USA because the country attribute has not been included.

**Comment by ANANDHSHANKARSUNDARARAJAN** [comment]
@eashwarsiddharth  If so  then it's simple i think
better you can ignore if it doesn't affect your objective much.

**Comment by Rajhan** [comment]
Currently ignore the geographical attributes. Social indicators for cities and states are beyond the scope. But if you find any prescription pattern among physicians between cities and states,probe and analyse it and share the work.

**Comment by Rajhan** [comment]
ignore the physicians with state=="ZZ". We want you guys to analyse the prescribing pattern of the physicians, whether it varies if they prescribe more branded drugs or generic one. and how PUF data impacts the prescribing data and vice versa.

**Comment by Rajhan** [comment]
HCC risk score of beneficiaries ,look into it.

**Comment by Rajhan** [comment]
@ANANDHSHANKARSUNDARARAJAN 
ML algorithms that can be applied to the given datasets.

Classification

Prescriber of Avonex vs Copaxone
Prescribers of Gilenya vs Copaxone
Prescribers of Branded vs Generics
Prediction
Prescribers of Namenda
Prescribers of Generics
