### ISSUE TITLE
City and nppes_provider_city

### ISSUE THREAD

**Issue by karthikeyann12** [sagitechls/SSN_SACE_2017_Jan#7]
Can the doctors city and nppes provider city be different? Well most of the cases are same.

> For example, a doctor in Statesville, NC is having nppes provider city has Mooresville, NC, which is about 18 miles apart. 

@sagitechls @Rajhan

**Comment by Rajhan** [comment]
A physician can practice at multiple locations(city and state).

**Comment by karthikeyann12** [comment]
Is it possible to create a classification modelling in the PUF dataset?

> I have this idea to merge and try a model with hcpcs class as target.
@Rajhan

**Comment by karthikeyann12** [comment]
Can a classification model be build in PUF dataset ? 
@Rajhan

**Comment by Rajhan** [comment]
@karthikeyann12 
yes. 

ML algorithms that can be applied to the given datasets.
 
Classification
1.	Prescriber of Avonex vs Copaxone 
2.	Prescribers of Gilenya vs Copaxone
3.	Prescribers of Branded vs Generics
Prediction
1.	Prescribers of Namenda
2.	Prescribers of Generics

**Comment by karthikeyann12** [comment]
@Rajhan  
Well I had a idea of classification based on hcpcs class, whether it will therapeutic/generic/others.
